name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup environment variables
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> $GITHUB_ENV
          echo "VITE_ANON_KEY=${{ secrets.VITE_ANON_KEY }}" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: |
          timeout 300 npx nuxi generate --fail-on-error --no-serve || true
          echo "Forcefully exiting process..."
          pkill -f "node" || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .output/public
          publish_branch: gh-pages
          # verbose: true
